[project]
name = "django-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
]

[dependency-groups]
dev = [
    "commitizen>=4.6.3",
]
